"""Check if Azure Search index has integrated vectorizer configured."""

import asyncio
import os
from pathlib import Path
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.indexes.aio import SearchIndexClient

# Load environment
try:
    from dotenv import load_dotenv
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        load_dotenv(env_path)
except ImportError:
    pass


async def check_index_config():
    """Check index configuration for integrated vectorization."""

    # Get credentials
    search_service = os.getenv("AZURE_SEARCH_SERVICE")
    search_endpoint = f"https://{search_service}.search.windows.net" if search_service else os.getenv("AZURE_SEARCH_ENDPOINT")
    index_name = os.getenv("AZURE_SEARCH_INDEX")
    api_key = os.getenv("AZURE_SEARCH_KEY")

    if not all([search_endpoint, index_name, api_key]):
        raise ValueError("Missing environment variables")

    print(f"Checking index: {index_name}")
    print(f"Endpoint: {search_endpoint}\n")

    # Create client
    credential = AzureKeyCredential(api_key)
    client = SearchIndexClient(endpoint=search_endpoint, credential=credential)

    try:
        # Get index
        index = await client.get_index(index_name)

        print("="*80)
        print("INDEX CONFIGURATION")
        print("="*80)

        # Check vectorizers
        print(f"\n[1] Vectorizers:")
        vectorizers = getattr(index, 'vectorizers', None)
        if vectorizers and len(vectorizers) > 0:
            print(f"    [OK] Found {len(vectorizers)} vectorizer(s)")
            for v in vectorizers:
                print(f"        - Name: {v.name}")
                print(f"          Type: {type(v).__name__}")
                if hasattr(v, 'parameters'):
                    params = v.parameters
                    if hasattr(params, 'deployment_name'):
                        print(f"          Deployment: {params.deployment_name}")
                    if hasattr(params, 'model_name'):
                        print(f"          Model: {params.model_name}")
        else:
            print("    [X] NO VECTORIZERS CONFIGURED!")
            print("        This is required for integrated vectorization.")
            print("        The index must have a vectorizer to generate embeddings.")

        # Check vector search profiles
        print(f"\n[2] Vector Search Configuration:")
        if index.vector_search and index.vector_search.profiles:
            print(f"    [OK] Found {len(index.vector_search.profiles)} profile(s)")
            for p in index.vector_search.profiles:
                vectorizer = p.vectorizer_name if hasattr(p, 'vectorizer_name') else None
                print(f"        - Profile: {p.name}")
                print(f"          Vectorizer: {vectorizer or '[NONE - client-side embeddings]'}")
                if hasattr(p, 'algorithm_configuration_name'):
                    print(f"          Algorithm: {p.algorithm_configuration_name}")
        else:
            print("    [X] No vector search configuration")

        # Check embeddings field
        print(f"\n[3] Embeddings Field:")
        embeddings_field = next((f for f in index.fields if f.name == 'embeddings'), None)
        if embeddings_field:
            print(f"    [OK] Field exists")
            print(f"        Type: {embeddings_field.type}")
            print(f"        Searchable: {embeddings_field.searchable}")
            print(f"        Dimensions: {embeddings_field.vector_search_dimensions}")
            print(f"        Profile: {embeddings_field.vector_search_profile_name}")
        else:
            print("    [X] Embeddings field not found!")

        # Summary
        print("\n" + "="*80)
        print("ANALYSIS")
        print("="*80)

        vectorizers = getattr(index, 'vectorizers', None)
        has_vectorizer = vectorizers and len(vectorizers) > 0
        has_profile_with_vectorizer = False

        if index.vector_search and index.vector_search.profiles:
            for p in index.vector_search.profiles:
                if hasattr(p, 'vectorizer_name') and p.vectorizer_name:
                    has_profile_with_vectorizer = True
                    break

        if has_vectorizer and has_profile_with_vectorizer:
            print("\n[SUCCESS] Index IS configured for integrated vectorization!")
            print("  - Vectorizer is configured")
            print("  - Vector profile uses the vectorizer")
            print("  - Embeddings will be generated by Azure Search")
            print("\nNext step: Wait a few minutes after uploading documents")
            print("for Azure Search to generate embeddings in the background.")
        elif embeddings_field and embeddings_field.vector_search_profile_name:
            if has_profile_with_vectorizer:
                print("\n[SUCCESS] Integrated vectorization is configured")
            else:
                print("\n[INFO] Index is configured for CLIENT-SIDE embeddings")
                print("  - Vector profile does NOT use a vectorizer")
                print("  - You must generate embeddings before upload")
                print("  - Set AZURE_USE_INTEGRATED_VECTORIZATION=false")
        else:
            print("\n[WARN] Index configuration unclear")
            print("  - Check vectorizer and profile configuration")

    finally:
        await client.close()


if __name__ == "__main__":
    asyncio.run(check_index_config())
