"""Test script to retrieve documents from Azure AI Search and verify embeddings."""

import asyncio
import sys
import os
from pathlib import Path

# Add parent directory to path to import modules
sys.path.insert(0, str(Path(__file__).parent.parent))

from azure.core.credentials import AzureKeyCredential
from azure.search.documents.aio import SearchClient
from config import load_config


async def check_embeddings_in_index():
    """Retrieve documents from index and check if embeddings are generated."""

    print("=" * 70)
    print("AZURE AI SEARCH - EMBEDDINGS VERIFICATION TEST")
    print("=" * 70)
    print()

    # Load configuration
    print("Loading configuration from .env...")
    try:
        config = load_config()
        print(f"✓ Configuration loaded successfully")
        print(f"  - Search Endpoint: {config.search.endpoint}")
        print(f"  - Index Name: {config.search.index_name}")
        print()
    except Exception as e:
        print(f"✗ Failed to load configuration: {e}")
        return

    # Create search client
    print("Connecting to Azure AI Search...")
    try:
        credential = AzureKeyCredential(config.search.api_key) if config.search.api_key else None
        search_client = SearchClient(
            endpoint=config.search.endpoint,
            index_name=config.search.index_name,
            credential=credential
        )
        print(f"✓ Connected to search index")
        print()
    except Exception as e:
        print(f"✗ Failed to connect to search: {e}")
        return

    # Retrieve sample documents
    print("Retrieving documents from index...")
    print("-" * 70)

    try:
        # Search for all documents (top 10)
        results = await search_client.search(
            search_text="*",
            top=10,
            select=["id", "sourcefile", "sourcepage", "content", "embeddings"]
        )

        documents = []
        async for result in results:
            documents.append(result)

        if not documents:
            print("✗ No documents found in the index")
            print("  Make sure you have run the pipeline to index documents first.")
            await search_client.close()
            return

        print(f"✓ Retrieved {len(documents)} documents")
        print()

        # Analyze embeddings
        print("=" * 70)
        print("EMBEDDINGS ANALYSIS")
        print("=" * 70)
        print()

        docs_with_embeddings = 0
        docs_without_embeddings = 0
        embedding_dimensions = set()

        for i, doc in enumerate(documents, 1):
            doc_id = doc.get("id", "unknown")
            sourcefile = doc.get("sourcefile", "unknown")
            sourcepage = doc.get("sourcepage", "unknown")
            content_preview = doc.get("content", "")[:50] + "..." if doc.get("content") else "No content"
            embeddings = doc.get("embeddings")

            print(f"Document {i}:")
            print(f"  ID: {doc_id}")
            print(f"  Source: {sourcefile}")
            print(f"  Page: {sourcepage}")
            print(f"  Content: {content_preview}")

            if embeddings and isinstance(embeddings, list) and len(embeddings) > 0:
                docs_with_embeddings += 1
                embedding_dimensions.add(len(embeddings))
                print(f"  ✓ Embeddings: PRESENT (dimension: {len(embeddings)})")
            else:
                docs_without_embeddings += 1
                print(f"  ✗ Embeddings: MISSING or EMPTY")

            print()

        # Summary
        print("=" * 70)
        print("SUMMARY")
        print("=" * 70)
        print(f"Total documents checked: {len(documents)}")
        print(f"Documents with embeddings: {docs_with_embeddings}")
        print(f"Documents without embeddings: {docs_without_embeddings}")

        if embedding_dimensions:
            print(f"Embedding dimensions found: {sorted(embedding_dimensions)}")

        print()

        if docs_with_embeddings == len(documents):
            print("✓ SUCCESS: All documents have embeddings generated!")
        elif docs_with_embeddings > 0:
            print("⚠ WARNING: Some documents are missing embeddings")
        else:
            print("✗ FAILURE: No documents have embeddings")
            print("  This might indicate:")
            print("  - Embeddings were not generated during indexing")
            print("  - Integrated vectorization is enabled (embeddings generated by Azure)")
            print("  - Pipeline configuration issue")

        print()

    except Exception as e:
        print(f"✗ Error during document retrieval: {e}")
        import traceback
        traceback.print_exc()

    finally:
        await search_client.close()
        print("Connection closed.")


def main():
    """Main entry point."""
    asyncio.run(check_embeddings_in_index())


if __name__ == "__main__":
    main()
