"""Verify Azure Search integrated vectorization is working correctly."""

import asyncio
import logging
import os
from pathlib import Path
from azure.core.credentials import AzureKeyCredential
from azure.search.documents.aio import SearchClient
from azure.search.documents.models import VectorizableTextQuery

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    # Look for .env in project root (parent of test_pipeline)
    env_path = Path(__file__).parent.parent / ".env"
    if env_path.exists():
        load_dotenv(env_path)
        print(f"[OK] Loaded environment from: {env_path}")
    else:
        load_dotenv()  # Try current directory
        print("[OK] Loaded environment from current directory")
except ImportError:
    print("[WARN] python-dotenv not installed, using existing environment variables")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


async def verify_integrated_vectorization():
    """Test that integrated vectorization is generating embeddings and vector search works."""

    # Load configuration
    search_service = os.getenv("AZURE_SEARCH_SERVICE")
    search_endpoint = f"https://{search_service}.search.windows.net" if search_service else os.getenv("AZURE_SEARCH_ENDPOINT")
    index_name = os.getenv("AZURE_SEARCH_INDEX")
    api_key = os.getenv("AZURE_SEARCH_KEY")

    if not all([search_endpoint, index_name, api_key]):
        raise ValueError("Missing required environment variables: AZURE_SEARCH_ENDPOINT/AZURE_SEARCH_SERVICE, AZURE_SEARCH_INDEX, AZURE_SEARCH_KEY")

    logger.info(f"Testing integrated vectorization on index: {index_name}")
    logger.info(f"Endpoint: {search_endpoint}")

    # Create search client
    credential = AzureKeyCredential(api_key)
    client = SearchClient(
        endpoint=search_endpoint,
        index_name=index_name,
        credential=credential
    )

    try:
        # Test 1: Check if documents exist
        logger.info("\n" + "="*80)
        logger.info("TEST 1: Checking if documents are indexed")
        logger.info("="*80)

        result = await client.search(search_text="*", top=1, include_total_count=True)
        total_docs = await result.get_count()
        logger.info(f"[OK] Found {total_docs} documents in index")

        if total_docs == 0:
            logger.error("[X] No documents found. Please upload documents first.")
            return False

        # Test 2: Check stored embeddings field
        logger.info("\n" + "="*80)
        logger.info("TEST 2: Checking stored embeddings field")
        logger.info("="*80)

        result = await client.search(
            search_text="*",
            select=["id", "embeddings", "content"],
            top=3
        )

        docs_with_embeddings = 0
        docs_without_embeddings = 0

        async for doc in result:
            doc_id = doc.get("id", "unknown")
            embeddings = doc.get("embeddings", None)
            content_preview = doc.get("content", "")[:100] + "..."

            if embeddings and len(embeddings) > 0:
                docs_with_embeddings += 1
                logger.info(f"  {doc_id}: [OK] Has embeddings ({len(embeddings)} dimensions)")
            else:
                docs_without_embeddings += 1
                logger.info(f"  {doc_id}: [X] No stored embeddings (expected with integrated vectorization)")
                logger.info(f"    Content: {content_preview}")

        logger.info(f"\nSummary:")
        logger.info(f"  Documents with stored embeddings: {docs_with_embeddings}")
        logger.info(f"  Documents without stored embeddings: {docs_without_embeddings}")

        if docs_without_embeddings > 0:
            logger.info("\n[INFO]  This is EXPECTED with integrated vectorization!")
            logger.info("   Embeddings are generated by Azure Search and stored internally.")

        # Test 3: Test vector search functionality
        logger.info("\n" + "="*80)
        logger.info("TEST 3: Testing vector search with integrated vectorization")
        logger.info("="*80)

        # Use VectorizableTextQuery to let Azure Search vectorize the query
        test_query = "pacing therapies"
        logger.info(f"Query: '{test_query}'")

        try:
            # Create vector query that will be vectorized by Azure Search
            vector_query = VectorizableTextQuery(
                text=test_query,
                k_nearest_neighbors=5,
                fields="embeddings"
            )

            result = await client.search(
                search_text=None,  # Pure vector search
                vector_queries=[vector_query],
                select=["id", "content", "sourcepage"],
                top=5
            )

            vector_results_count = 0
            async for doc in result:
                vector_results_count += 1
                doc_id = doc.get("id", "unknown")
                sourcepage = doc.get("sourcepage", "N/A")
                content_preview = doc.get("content", "")[:150].replace("\n", " ")

                logger.info(f"\n  Result {vector_results_count}: {doc_id}")
                logger.info(f"    Source: {sourcepage}")
                logger.info(f"    Content: {content_preview}...")

            if vector_results_count > 0:
                logger.info(f"\n[SUCCESS] SUCCESS! Vector search returned {vector_results_count} results")
                logger.info("   This confirms integrated vectorization is WORKING correctly!")
                logger.info("   Azure Search generated embeddings and used them for similarity search.")
                return True
            else:
                logger.warning("[WARN]  Vector search returned 0 results")
                logger.warning("   Possible reasons:")
                logger.warning("   1. Embeddings are still being generated (try again in a few minutes)")
                logger.warning("   2. Index vectorizer not configured correctly")
                logger.warning("   3. Query doesn't match any content")
                return False

        except Exception as e:
            logger.error(f"[X] Vector search failed: {e}")
            logger.error("  This may indicate:")
            logger.error("  1. Index doesn't have a vectorizer configured")
            logger.error("  2. VectorizableTextQuery not supported (older API version)")
            logger.error("  3. Embeddings field not configured for vector search")
            return False

        # Test 4: Test hybrid search (text + vector)
        logger.info("\n" + "="*80)
        logger.info("TEST 4: Testing hybrid search (keyword + vector)")
        logger.info("="*80)

        try:
            vector_query = VectorizableTextQuery(
                text=test_query,
                k_nearest_neighbors=5,
                fields="embeddings"
            )

            result = await client.search(
                search_text=test_query,  # Keyword search
                vector_queries=[vector_query],  # + Vector search
                select=["id", "content", "sourcepage"],
                top=5
            )

            hybrid_results_count = 0
            async for doc in result:
                hybrid_results_count += 1
                doc_id = doc.get("id", "unknown")
                logger.info(f"  {hybrid_results_count}. {doc_id}")

            if hybrid_results_count > 0:
                logger.info(f"\n[SUCCESS] Hybrid search returned {hybrid_results_count} results")
                logger.info("   Combined keyword + vector search is working!")

        except Exception as e:
            logger.warning(f"[WARN]  Hybrid search failed: {e}")

    finally:
        await client.close()

    return True


async def main():
    """Main entry point."""
    try:
        success = await verify_integrated_vectorization()

        print("\n" + "="*80)
        if success:
            print("[SUCCESS] VERIFICATION COMPLETE: Integrated vectorization is working!")
            print("="*80)
            print("\nKey Findings:")
            print("  • Documents are indexed in Azure Search")
            print("  • Stored embeddings field may be empty (expected)")
            print("  • Vector search queries return relevant results")
            print("  • Azure Search is generating embeddings in the background")
            print("\nConclusion: Your integrated vectorization setup is correct! [OK]")
        else:
            print("[WARN]  VERIFICATION INCOMPLETE: Some issues detected")
            print("="*80)
            print("\nPlease check the logs above for details.")
        print("="*80)

    except Exception as e:
        logger.error(f"Verification failed with error: {e}", exc_info=True)


if __name__ == "__main__":
    asyncio.run(main())
